# Generated by Django 2.2.7 on 2019-11-19 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport_sections', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='sport_interests',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('district', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=2)),
                ('sport_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sport_sections.Sport_Section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
