# Generated by Django 2.2.7 on 2019-12-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191119_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pupil',
        ),
    ]
